import { Server, Channel, Message, ServerMember } from '@/types/database';

export const DEMO_SERVERS: Server[] = [
  {
    id: 'server-playverse',
    name: 'PlayVerse Official',
    icon_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&h=128&fit=crop&crop=faces',
    invite_code: 'PLAYVERSE',
    owner_id: 'demo-user-001',
    created_at: new Date().toISOString(),
  },
  {
    id: 'server-gaming',
    name: 'Gamer Lounge 🎮',
    icon_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=128&h=128&fit=crop&crop=faces',
    invite_code: 'GAMING2026',
    owner_id: 'demo-user-002',
    created_at: new Date().toISOString(),
  },
  {
    id: 'server-devs',
    name: 'Dev Community 💻',
    icon_url: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=128&h=128&fit=crop&crop=faces',
    invite_code: 'DEVCOMM',
    owner_id: 'demo-user-003',
    created_at: new Date().toISOString(),
  },
];

export const DEMO_CHANNELS: Record<string, Channel[]> = {
  'server-playverse': [
    { id: 'ch-general', server_id: 'server-playverse', name: 'chung', type: 'text', topic: 'Kênh thảo luận chung của cộng đồng PlayVerse', created_at: new Date().toISOString() },
    { id: 'ch-announcements', server_id: 'server-playverse', name: 'thông-báo', type: 'text', topic: 'Tin tức & cập nhật mới nhất', created_at: new Date().toISOString() },
    { id: 'ch-showcase', server_id: 'server-playverse', name: 'khoe-góc-máy', type: 'text', topic: 'Nơi khoe setup, dự án cá nhân', created_at: new Date().toISOString() },
    { id: 'ch-voice-1', server_id: 'server-playverse', name: 'Phòng Tám Chuyện 1', type: 'voice', topic: null, created_at: new Date().toISOString() },
    { id: 'ch-voice-2', server_id: 'server-playverse', name: 'Phòng Stream Game', type: 'voice', topic: null, created_at: new Date().toISOString() },
  ],
  'server-gaming': [
    { id: 'ch-gaming-general', server_id: 'server-gaming', name: 'sảnh-chờ', type: 'text', topic: 'Tìm đồng đội chiến game', created_at: new Date().toISOString() },
    { id: 'ch-gaming-voice', server_id: 'server-gaming', name: 'Voice Chiến Game', type: 'voice', topic: null, created_at: new Date().toISOString() },
  ],
  'server-devs': [
    { id: 'ch-dev-chat', server_id: 'server-devs', name: 'hỏi-đáp-code', type: 'text', topic: 'Next.js, Supabase, Tailwind, TypeScript', created_at: new Date().toISOString() },
    { id: 'ch-dev-resources', server_id: 'server-devs', name: 'tài-nguyên-hay', type: 'text', topic: 'Thư viện, tài liệu miễn phí', created_at: new Date().toISOString() },
  ],
};

export const DEMO_MEMBERS: Record<string, ServerMember[]> = {
  'server-playverse': [
    {
      id: 'mem-1',
      server_id: 'server-playverse',
      profile_id: 'demo-user-001',
      role: 'owner',
      joined_at: new Date().toISOString(),
      profile: {
        id: 'demo-user-001',
        username: 'PlayVerseUser',
        display_name: 'Hoàng (Admin)',
        avatar_url: 'https://api.dicebear.com/7.x/bottts/svg?seed=playverse',
        status: 'online',
        custom_status: 'Đang phát triển PlayVerse 🚀',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    },
    {
      id: 'mem-2',
      server_id: 'server-playverse',
      profile_id: 'demo-user-002',
      role: 'admin',
      joined_at: new Date().toISOString(),
      profile: {
        id: 'demo-user-002',
        username: 'AlexNguyen',
        display_name: 'Alex Nguyễn',
        avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alex',
        status: 'idle',
        custom_status: 'AFK ăn trưa 🍜',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    },
    {
      id: 'mem-3',
      server_id: 'server-playverse',
      profile_id: 'demo-user-003',
      role: 'moderator',
      joined_at: new Date().toISOString(),
      profile: {
        id: 'demo-user-003',
        username: 'MinhTech',
        display_name: 'Minh Dev',
        avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=minh',
        status: 'dnd',
        custom_status: 'Đang fix bug, đừng tag 🛑',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    },
    {
      id: 'mem-4',
      server_id: 'server-playverse',
      profile_id: 'demo-user-004',
      role: 'member',
      joined_at: new Date().toISOString(),
      profile: {
        id: 'demo-user-004',
        username: 'LinhChi',
        display_name: 'Linh Chi',
        avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=linh',
        status: 'online',
        custom_status: 'Nghe nhạc Chill 🎧',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    },
    {
      id: 'mem-5',
      server_id: 'server-playverse',
      profile_id: 'demo-user-005',
      role: 'member',
      joined_at: new Date().toISOString(),
      profile: {
        id: 'demo-user-005',
        username: 'DucGamer',
        display_name: 'Đức Pro',
        avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=duc',
        status: 'offline',
        custom_status: null,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    },
  ],
};

export const DEMO_MESSAGES: Record<string, Message[]> = {
  'ch-general': [
    {
      id: 'msg-1',
      channel_id: 'ch-general',
      profile_id: 'demo-user-001',
      content: 'Chào mừng tất cả các bạn đến với **PlayVerse**! 🚀\nĐây là máy chủ trò chuyện độc lập chạy trên nền tảng Supabase và tên miền `playverse.senexam.me`.',
      attachments: [],
      reply_to_id: null,
      is_pinned: true,
      created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
      updated_at: new Date(Date.now() - 3600000 * 2).toISOString(),
      profile: {
        id: 'demo-user-001',
        username: 'PlayVerseUser',
        display_name: 'Hoàng (Admin)',
        avatar_url: 'https://api.dicebear.com/7.x/bottts/svg?seed=playverse',
        status: 'online',
        custom_status: 'Đang phát triển PlayVerse 🚀',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    },
    {
      id: 'msg-2',
      channel_id: 'ch-general',
      profile_id: 'demo-user-002',
      content: 'Giao diện mượt mà và tối ưu y hệt Discord luôn! Dữ liệu của chúng ta giờ hoàn toàn do chúng ta tự chủ 🔒',
      attachments: [],
      reply_to_id: null,
      is_pinned: false,
      created_at: new Date(Date.now() - 3600000).toISOString(),
      updated_at: new Date(Date.now() - 3600000).toISOString(),
      profile: {
        id: 'demo-user-002',
        username: 'AlexNguyen',
        display_name: 'Alex Nguyễn',
        avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alex',
        status: 'idle',
        custom_status: 'AFK ăn trưa 🍜',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    },
    {
      id: 'msg-3',
      channel_id: 'ch-general',
      profile_id: 'demo-user-004',
      content: 'Tuyệt vời quá! Kênh thoại và gửi tin nhắn thời gian thực nhanh không có độ trễ luôn nè ❤️',
      attachments: [],
      reply_to_id: null,
      is_pinned: false,
      created_at: new Date(Date.now() - 1800000).toISOString(),
      updated_at: new Date(Date.now() - 1800000).toISOString(),
      profile: {
        id: 'demo-user-004',
        username: 'LinhChi',
        display_name: 'Linh Chi',
        avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=linh',
        status: 'online',
        custom_status: 'Nghe nhạc Chill 🎧',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    },
  ],
};
